services:
  app:
    image: nsh4r/backend-app:0.0.1
    restart: always
    ports:
      - "20000:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/opt/app

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "55432:${DB_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data