services:
  app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8080"
#    env_file:
#      - .env
    depends_on:
      - postgres
    volumes:
      - .:/opt/app
    command: ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]

  postgres:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:${DB_PORT}"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
#    volumes:
#      - postgres_data:/var/lib/postgresql/data