name: KUBSAU-ProfTest-CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_VERSION: ${{ github.run_number }}

jobs:
  BuildTestPublish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{vars.POSTGRES_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Set Up Python Environment.
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pipx install poetry==1.7.0
          poetry env use 3.12
          poetry install --with test

      - name: Run static code analysis with flake8
        run: poetry run flake8 . --count --show-source --statistics
        continue-on-error: true

#      - name: Run Database Migrations.
#        run: python3 manage.py migrate

      - name: Run Unit Tests
        run: |
          poetry run pytest -v

      - name: Build + Tag Image.
        run: docker build -t backend-app:${{ env.IMAGE_VERSION }} -f Dockerfile.app .

      - name: Scan Docker Image with Snyk.
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          image: backend-app:${{ env.IMAGE_VERSION }}
          args: --file=Dockerfile.app
        continue-on-error: true
#
#      - name: Configure AWS Credentials
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        uses: aws-actions/configure-aws-credentials@v1.7.0
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ env.REGION }}

      - name: Publish Docker Image.
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          aws ecr get-login-password --region ${{ env.REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}
          docker push backend-app:${{ env.IMAGE_VERSION }}
#

